### ISSUE TITLE
Implementação do CDU: Manter Serviço

### ISSUE THREAD

**Issue by Gilbert-Silva** [PI-InfoWeb-CNAT/agendamento_energia#17]
Implementar o CDU no projeto do Visual Studio, contemplando as camadas do padrão MVC. inserir link na página principal para a página do cadastro de serviços

**Comment by ViniciusDeMorais46290** [comment]
Criar PartialPage para conter a versão fake do layout de página de Admin ( onde ao invés de sistema e agendamento, aparecerá Sistema Agendamento, Produto Serviço e Horarios )
